<div class="col-sm-3 col-md-2 sidebar" id="prueba">
    <ul class="nav nav-sidebar">
    <li class="active"><a href="<?=BASE_URL?>">Inicio<span class="glyphicon glyphicon-home pull-right"></span></a></li>
    
    <?php foreach($menu as $m1): ?>
    
        <?php if(isset($m['id'])): ?>
            <?php $_style = 'active'; ?>
        <?php else: ?>
            <?php $_style = ''; ?>
        <?php endif; ?>
        
        <?php if(isset($m1['divider']) && $m1['divider']): ?>
            <li class="divider"></li>
        <?php endif; ?>
        
    <li class="menu-item dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="<?=$m1['enlace']?>"><?=$m1['titulo']?> 
            <span class="glyphicon <?=$m1['imagen']?> pull-right"></span></a>
    <ul class="dropdown-menu">        
        <?php foreach($m1 as $k1=>$v1): ?>
            <?php if (is_array($v1)): ?>  
    <li>
        <a href="<?=$v1['enlace']?>"><?=$v1['titulo']?>
            <span class="glyphicon <?=$v1['imagen']?> pull-right"></span>
        </a>
    </li>
               <?php if($v1['divider'] == 1): ?>
    <li class="divider"></li>
               <?php endif; ?>
                 
            <?php endif; ?>     
        <?php endforeach; ?>
     </ul>   
    <?php endforeach; ?>
    </li>   
    </ul>
</div>
